control_chassis:
  ros__parameters:
    motor_positions: [
      #  X            Y         Z        phi      theta
        0.2789,   0.2461,   -0.0191,     0.0,    -45.0,
        0.2789,  -0.2461,   -0.0191,     0.0,     45.0,
       -0.2789,  -0.2461,   -0.0191,     0.0,    135.0,
       -0.2789,   0.2461,   -0.0191,     0.0,   -135.0,
        0.290,    0.0,      -0.0243,   -90.0,      0.0,
        0.0,     -0.2649,   -0.0243,   -90.0,      0.0,
       -0.290,    0.0,      -0.0243,   -90.0,      0.0,
        0.0,      0.2649,   -0.0243,   -90.0,      0.0,
    ] # flattend 5 * 8 matrix
    motor_lower_bounds: [ -49.42552, -49.42552, -49.42552, -49.42552, -49.42552, -49.42552, -49.42552, -49.42552 ]
    motor_upper_bounds: [ 64.23356, 64.23356, 64.23356, 64.23356, 64.23356, 64.23356, 64.23356, 64.23356 ]
    axis_weight_matrix: [
       1.0,   0.0,   0.0,  0.0,  0.0,  0.0,
       0.0,   1.0,   0.0,  0.0,  0.0,  0.0,
       0.0,   0.0,   1.0,  0.0,  0.0,  0.0,
       0.0,   0.0,   0.0,  1.0,  0.0,  0.0,
       0.0,   0.0,   0.0,  0.0,  1.0,  0.0,
       0.0,   0.0,   0.0,  0.0,  0.0,  1.0,
    ] # flattend 6 * 6 matrix

    pid_gains_vel_linear: [ 20000.0, 0.0, 0.0 ]
    pid_gains_vel_angular: [ 100.0, 0.0, 0.0 ]

    pid_gains_pose_linear: [ 300.0, 0.0, 12.0 ]
    pid_gains_pose_angular: [ 60.0, 0.0, 10.0 ]

    # pid_gains_vel_linear: [ 0.0, 0.0, 0.0 ]
    # pid_gains_vel_angular: [ 0.0, 0.0, 0.0 ]

    # pid_gains_pose_linear: [ 0.0, 0.0, 0.0 ]
    # pid_gains_pose_angular: [ 0.0, 0.0, 0.0 ]

    pose_lock_deadband: [ 0.1, 0.1, 0.1, 0.1, 0.1, 0.1 ]

    drag_effect_matrix: [
       1.0,  0.0,  0.0,  0.0,  0.0,  0.0,
       0.0,  1.0,  0.0,  0.0,  0.0,  0.0,
       0.0,  0.0,  1.0,  0.0,  0.0,  0.0,
       0.0,  0.0,  0.0,  1.0,  0.0,  0.0,
       0.0,  0.0,  0.0,  0.0,  1.0,  0.0,
       0.0,  0.0,  0.0,  0.0,  0.0,  1.0,
    ] # flattend 6 * 6 matrix

    drag_coefficients: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
    drag_areas: [ 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 ]
    water_density: 1000.0 # kg/m^3
    robot_volume: 0.03963 # m^3
    robot_mass: 33.5 # kg
    center_of_buoyancy: [ 0.0, 0.0, 0.0 ]
    qp_epsilon: 0.001