<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>guppy_control</name>
  <version>0.0.0</version>
  <description>ros2_control implementation of Guppy hardware and control, including thrust allocation and thruster interface.</description>
  <maintainer email="colewilson.main@gmail.com">Palouse RoboSub</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ros2_control</depend>
  <depend>proxsuite</depend>
  <depend>control_toolbox</depend>
  <depend>std_srvs</depend>
  <depend>guppy_msgs</depend>
  <depend>guppy_util</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
