# type constants
string   TYPE_INFO    = "info"
string   TYPE_SUCCESS = "success"
string   TYPE_WARNING = "warning"
string   TYPE_ERROR   = "error"

# position constants
uint32   POSITION_TOP_LEFT     = 0x00000
uint32   POSITION_TOP_RIGHT    = 0x00000
uint32   POSITION_BOTTOM_LEFT  = 0x00000
uint32   POSITION_BOTTOM_RIGHT = 0x00000

# theme constants
string   THEME_LIGHT = "Light"
string   THEME_DARK  = "Dark"
string   THEME_COLOR = "Color"

string   type                "info"
uint32   position            0x00000
string   theme               "Dark"
bool     close_on_click      true
uint16   auto_close          2500
bool     hide_progress_bar   true
