name: ROS2 Jazzy CI

on:
  push:
    branches: [ "**" ]

jobs:
  changes:
      runs-on: ubuntu-24.04
      outputs:
        code: ${{ steps.filter.outputs.code }}
      steps:
        - name: Checkout guppy 
          uses: actions/checkout@v4

        - name: Filter for code changes
          uses: dorny/paths-filter@v3
          id: filter
          with:
            filters: |
              code:
                - '**/*.cpp'
                - '**/*.hpp'
                - '**/*.py'
                - '**/CMakeLists.txt'
                - '**/package.xml'
                - 'flake.nix'
                - 'flake.lock'
                - '.github/workflows/**'

  # flake-check:
  #   needs: changes
  #   if: needs.changes.outputs.code == 'true'
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Checkout guppy
  #       uses: actions/checkout@v4

  #     - name: Install Determinate Nix
  #       uses: DeterminateSystems/nix-installer-action@main

  #     - name: Cache Nix Store
  #       uses: DeterminateSystems/magic-nix-cache-action@main
        
  #     - name: Check Nix Flake Validity
  #       run: nix flake check

  build_and_test_ros2:
    needs: changes
    if: needs.changes.outputs.code == 'true'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout guppy
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install Determinate Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cache Nix Store
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Nix Flake
        uses: DeterminateSystems/flake-checker-action@main

      - name: Build and run tests
        run: nix develop --accept-flake-config --command bash -c "./.github/workflows/diff_and_build.sh"
